### PR TITLE
Added getter and setter functionality to Protocol's dosage function.

### LINKED ISSUE #67: Add getter and setter functionality to Protocol.dose()
Protocol.dose() currently doesn't allow the user to adjust the dosing protocol function. 

- [x] Implement a getter-and-setter method in Protocol that takes a function as input then assigns the attribute Protocol.dose_function to the input

### PR DESCRIPTION
**Pull request by jewh**
Added getter method Protocol.dose - accesses dose(t) function, name 'dose' preserved so as not to break new Solution methods. 
Added setter method add_dosage_function - allows the user to alter the dose(t) function by passing a new function. 

Closes #67.

### CODE REVIEW

**Comment by jewh** [comment]
Appears to be failing unit tests as protocol.dose() no longer returns a function, rather protocol.dose does.

**Comment by smf541** [comment]
> Appears to be failing unit tests as protocol.dose() no longer returns a function, rather protocol.dose does.

So can we fix this by changing the test? test_protocol.py line 73 would be "dose = protocol.dose" instead?

**Comment by jewh** [comment]
> > Appears to be failing unit tests as protocol.dose() no longer returns a function, rather protocol.dose does.
> 
> So can we fix this by changing the test? test_protocol.py line 73 would be "dose = protocol.dose" instead?

Yeah I think so

**Comment by caitlinashcroft** [comment]
Looks great :D :D :D <3 <3 <3

**Pull request merged**
